# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTBVV-afMRksaYDzo1flQhQ--zUEACVK
"""

#importing libraries
import pandas as pd
import json

#loading the json file
df=pd.read_json("/content/trends_20260413.json")

df.head()

#to find out how many rows and columns
df.shape

#to know about the data types and check if they are correct.
df.info()

# to find out number of null values in each column
df.isna().sum()

#to find out the duplicate rows in the data set
df.duplicated().sum()

#displaying the rows where score<5
df[df["score"]<5]

#df

#Removing the rows where score<5
df.drop(df[df["score"]<5].index,inplace=True)
print("number of rows remaining after removing the rows where score<5 : ",len(df))

df

#removing any rows with the same post_id
df=df.drop_duplicates(subset="post_id")
print("number of rows remaining after removing duplicated: ", len(df))

#stripping extra spaces from the title column
df["title"]=df["title"].str.strip()

#Saving the dataframe into a csv file
df.to_csv("sample_data/trends_clean.csv",index=False)

print(f"Saved {len(df)} rows to trends_clean.csv")

category_counts=df["category"].value_counts()

print("Stories per Category:")
print(category_counts)