# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o2neRF7XGFRc0iT32-mseY1alHba3_7r
"""

import time
import requests
from datetime import datetime
import json
import os

#Fetching ids from the url using requests
url = "https://hacker-news.firebaseio.com/v0/topstories.json"
headers = {"User-Agent": "TrendPulse/1.0"}

#using requests get method to fetch inside response object
response = requests.get(url, headers=headers)
ids=response.json()

#print(ids)

#creating empty stories list
stories=[]
headers = {"User-Agent": "TrendPulse/1.0"}
#fetching each story details
for sid in ids:
    try:
        url = f"https://hacker-news.firebaseio.com/v0/item/{sid}.json"
        response = requests.get(url, headers=headers)
        response.raise_for_status()  # raises error if bad response

        stories.append(response.json()) #append every json dictionary to stories list

    except requests.exceptions.RequestException as e:
        print(f"Error fetching {sid}: {e}")

#print(stories)

#stories[0]["title"]

#creating categories dictionary with each category and its keywords
categories = {
    "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports":["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]

}

#function that check matching keywords with title and findout the category
def get_category(title):
  title=title.lower()
  for category,keywords in categories.items():
    for word in keywords:
      if word in title:
        return category
  return None

#function that fetch all story details and make required fields and push into a list
def fetch_data():
  collected=[]
  category_count={cat:0 for cat in categories}
  for i in range(0,500):

      category=get_category(stories[i]["title"])
      if category and category_count[category]<25:
        story={
          "post_id": stories[i]["id"],
          "title":stories[i]["title"],
          "category":category,
          "score":stories[i]["score"],
          "num_comments":stories[i]["descendants"],
          "author":stories[i]["by"],
          "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
        collected.append(story)
        category_count[category]+=1
      if all(v>=25 for v in category_count.values()):
        break
  return collected

#calling the function and save the list into data
data=fetch_data()

#print(data)

#Function that save the data into a json file in required format
def save_json(data):
  os.makedirs("data",exist_ok=True)
  filename=f"data/trends_{datetime.now().strftime("%Y%m%d")}.json"

  with open(filename,"w") as f:
    json.dump(data,f,indent=4)

  print(f"collected {len(data)} stories, saved to {filename}")

#Function calling of save_json()
save_json(data)