# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S8QxQiAui68RmF8-YwgsJRDZoF-9f_me
"""

#importing libraries
import pandas as pd
import numpy as np

#loading csv file from task 2
df=pd.read_csv("/content/trends_clean.csv")

df

#showing first 5 rows
df.head()

print("first 5 rows: ",df.head())

#Showing its shape, rows and columns
df.shape

print("shape: ",df.shape)

#Average of score for all stories
df["score"].mean()
print("Average Score: ",df["score"].mean())

#Average of num_comments for all stories
df["num_comments"].mean()
print("Average of num_comments: ",df["num_comments"].mean())

df.describe()

#chaniging the score column to numpy series
scores=df["score"].to_numpy()

#calculating mean, median, std of scores using numpy
print("Mean of scores using numpy: ",np.mean(scores))

print("Median of scores using numpy: ",np.median(scores))

print("Std of scores using numpy: ",np.std(scores))

#highest score
highest_score=np.max(scores)
print("Highest Score: ",highest_score)

#lowest score
lowest_score=np.min(scores)
print("Lowest Score: ",lowest_score)

#Category with highest stories
top_category=df["category"].value_counts().idxmax()
print("Category with most stories: ",top_category)

#Story with most comments
top_story=df.loc[df["num_comments"].idxmax()]

print("Title of story with high number of comments: ",top_story["title"])
print("Comment count: ",top_story["num_comments"])

#Adding new column "engagement" using formula
df["engagement"]=df["num_comments"]/(df["score"]+1)

df

#Adding new column "ispopular"
df["is_popular"]=df["score"]>df["score"].mean()

df

#Saving analysed data to csv file
df.to_csv("sample_data/trends_analysed.csv",index=False)
print("Saved the csv file")