# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GSbp5HKzyFomx--iLpVgMWlifWE34vlt
"""

#importing libraries
import pandas as pd
import matplotlib.pyplot as plt

#loding the csv file from task 3
df=pd.read_csv("/content/trends_analysed.csv")

df

df.info()

#Horizontal bar graph for top 10 stories by score
top10=df.nlargest(10,"score")
plt.barh(top10["title"],top10["score"],color="red")
plt.title("Top 10 Stories by scores")
plt.xlabel("Scores")
plt.ylabel("Stories")
plt.savefig("chart1_top_stories.png")
plt.show()

#Bar graph of Stories per category
count=df["category"].value_counts()
plt.bar(count.index,count.values,color="red")
plt.title("Number of stories per category")
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.savefig("chart2_categories.png")
plt.show()

#Scatter plot of Score Vs Comments
plt.scatter(df["score"],df["num_comments"], c=df["is_popular"])
plt.title("Score vs Number of comments")
plt.xlabel("Score")
plt.ylabel("Comments")
plt.savefig("chart3_scatter.png")
plt.show()

#Dashboard : Combining all 3 charts
plt.subplot(1,3,1)
top10=df.nlargest(10,"score")
plt.barh(top10["title"],top10["score"],color="red")
plt.title("Top 10 Stories by scores")

plt.subplot(1,3,2)
count=df["category"].value_counts()
plt.bar(count.index,count.values,color="red")
plt.xticks(rotation=90)

plt.title("Number of stories per category")

plt.subplot(1,3,3)
plt.scatter(df["score"],df["num_comments"], c=df["is_popular"])
plt.title("Score vs Number of comments")


plt.savefig("dashboard.png")
plt.show()